import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Planet from "@/components/Planet";
import Tabs from "@/components/Tabs";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>The planets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Antonio:wght@500;700&family=League+Spartan:wght@700&family=Manrope:wght@500;700&family=Overpass:wght@400;700&display=swap');
        </style>
      </Head>

      <main>
        <Tabs></Tabs>
        <div className={styles.container}>
          <Planet></Planet>
        </div>
      </main>
    </>
  );
}
