import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Planet from "@/components/Planet/Planet";
import Tabs from "@/components/Tabs/Tabs";
import contentfulClient from "@/contentful";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const getStaticPaths = async () => {
  const response = await contentfulClient.getEntries({
    content_type: "planet",
  });

  const paths = response.items.map((planet) => {
    return {
      params: { planetName: planet.fields.name.toLowerCase() },
    };
  });
  console.log("What is PATHS?", paths);
  return {
    paths: paths,
    fallback: false, // false or "blocking"
  };
};

export async function getStaticProps(context) {
  console.log("WAAR IS CONTEXT?", context.params.planetName);
  const response = await contentfulClient.getEntries({
    content_type: "planet",
  });

  // console.log("WAAR Is RESPONSE?", response.items);
  const planet = response.items.find((planet) => {
    console.log("WAAR IS PLANET.fields?", planet.fields.name);
    console.log("WAT IS PLANETNAME?", context.params.planetName);
    return planet.fields.name.toLowerCase() === context.params.planetName;
  });
  console.log("WAT IS PLANET?", planet);
  // const planet = await contentfulClient.getEntry("27C2UuoEP1TObaH2kgPFIe");
  // console.log(planet.fields.imgOverview.fields.file.url);
  return {
    props: { planet: planet },
  };
}

export default function Home(props) {
  console.log(props);

  const [additionalInfo, setAdditionalInfo] = useState("Overview");
  // console.log("WHAT IS ADDITIONAL INFO?", additionalInfo);

  const router = useRouter();
  // console.log("WHAT IS ROUTER?", router);

  function handleclick(infoValue) {
    setAdditionalInfo(infoValue);
  }

  useEffect(() => {
    setAdditionalInfo("Overview");
    // console.log("I'm rendering");
  }, [router.query.planetName]);

  return (
    <>
      <Head>
        <title>The planets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Antonio:wght@500&family=League+Spartan:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Tabs></Tabs>
        <div className={styles.container}>
          <Planet
            handleclick={handleclick}
            name={props.planet.fields.name}
            img={props.planet.fields[`img${additionalInfo}`].fields.file.url}
            // img={props.planet.fields.imgStructure.fields.file.url}
            // img={props.planet.fields.imgGeology.fields.file.url}
            contentDesc={props.planet.fields[`description${additionalInfo}`]}
            // structure={props.planet.fields.descriptionStructure}
            // geology={props.planet.fields.descriptionGeology}
            sourcelink={props.planet.fields.sourcelink}
            rotation={props.planet.fields.rotation}
            revolution={props.planet.fields.revolution}
            radius={props.planet.fields.radius}
            temperature={props.planet.fields.temperature}
          ></Planet>
        </div>
      </main>
    </>
  );
}
